// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: Prisma generate doesn't need a real connection, only the schema

// Only load dotenv/config if available (for local development)
// During Vercel build, DATABASE_URL will be available from environment variables
try {
  require("dotenv/config");
} catch (e) {
  // dotenv not available, that's OK - environment variables will be set by Vercel
}

// Use dummy URL during build if DATABASE_URL is not available
// Prisma generate doesn't need a real connection, only the schema
// This allows prisma generate to work during Vercel build without DATABASE_URL
const databaseUrl =
  process.env.DATABASE_URL || "mongodb://localhost:27017/dummy?appName=PrismaGenerate";

// Only export config if prisma/config is available
try {
  const { defineConfig } = require("prisma/config");
  
  module.exports = defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
      path: "prisma/migrations",
    },
    datasource: {
      url: databaseUrl,
    },
  });
} catch (e) {
  // prisma/config not available, that's OK - Prisma will use schema.prisma directly
  // This can happen during build if the package isn't installed yet
  module.exports = {};
}
